version: 1.6.{build}
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: OrangeJetpack.Localization\bin\Release\OrangeJetpack.Localization.dll
  name: OrangeJetpack.Localization.dll
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: FzrDwPQx7c8FvZ1edcp+yE4lJx75Q3MfCXlobdBjtA2XP60134X6W0BuN43fF8H/HuK7K6OHfTICzcCcbcAyHv1ZjQ8wDuhDngaHy2d749w=
  on:
    branch: master