version: 1.7.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: /.*\.nupkg/
deploy:
- provider: NuGet
  api_key:
    secure: csMfQhbKLQy5CWIrau/G+Im6A/TRXV1KuViM4YBRMJyWDBo84QzIfSnDt2a9djcvnC2xeOj1QZ4kx2T8EVbUalB6UpFpfhlu7i9k4T8DXSI=
  on:
    branch: master